### ISSUE TITLE
Bootloop

### ISSUE THREAD

**Issue by DavidBoyes** [shuuryou/f22pro#1]
Do you have any idea how to get the device out of a boot loop? It repeats duoqin screen then black screen. I've tried various key combos while turning on after disconnecting the battery but nothing seems to work. Thanks

**Comment by shuuryou** [comment]
I'm afraid to say that if it won't boot into the factory test menu (VOLUME UP + VOLUME DOWN + plug in USB) or Fastboot (VOLUME UP + plug in USB) or the MTK preloader (VOLUME DOWN + plug in USB) anymore, you've got a paperweight. If you can get into Fastboot or the preloader you can work from there to restore a known-good ROM.

**Comment by DavidBoyes** [comment]
I managed to get it to connect to mtk in the end, my MacBook wasn't doing it but a steam deck did. Thanks
